-- Add new fields to pets table for more complete pet profiles

-- Medical and health information
ALTER TABLE pets ADD COLUMN IF NOT EXISTS blood_type VARCHAR(10);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS allergies VARCHAR(500);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS medical_conditions VARCHAR(500);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS vet_name VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS vet_phone VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS vet_address VARCHAR(255);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS last_vaccination_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS next_vaccination_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS last_vet_visit DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS insurance_provider VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS insurance_policy_number VARCHAR(100);

-- Additional pet information
ALTER TABLE pets ADD COLUMN IF NOT EXISTS emergency_contact VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS emergency_phone VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS adoption_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS adoption_center VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS registration_number VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS license_number VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS license_expiry_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS spayed_neutered BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS spayed_neutered_date DATE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS deceased BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS date_deceased DATE;

-- Behavior and characteristics
ALTER TABLE pets ADD COLUMN IF NOT EXISTS temperament VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS energy_level VARCHAR(20);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS training_level VARCHAR(50);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS favorite_activities VARCHAR(255);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS favorite_food VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS special_needs VARCHAR(500);

-- Security and location
ALTER TABLE pets ADD COLUMN IF NOT EXISTS last_known_location VARCHAR(100);
ALTER TABLE pets ADD COLUMN IF NOT EXISTS lost BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pets ADD COLUMN IF NOT EXISTS lost_date DATE;